// Code generated by goagen v1.4.0, DO NOT EDIT.
//
// API "cellar": Application User Types
//
// Command:
// $ goagen
// --design=api/design
// --out=$(GOPATH)/src/api
// --version=v1.4.0

package app
